spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}
  cloud:
    vault:
      generic:
        enabled: true
        profile-separator: '/'
        default-context: discovery-service
server:
  port: 8761
eureka:
  login: ${EUREKA_LOGIN}
  password: ${EUREKA_PASSWORD}
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
